spring:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/test_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    mapper-locations: classpath:/mapper/**/*.xml



